/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Conexion;

import java.sql.Connection;
import java.util.Locale;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.*;

/**
 *
 * @author GIANELA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton4 = new javax.swing.JButton();
        bsalir1 = new javax.swing.JLabel();
        bcamion = new javax.swing.JLabel();
        bconductor = new javax.swing.JLabel();
        bboleto = new javax.swing.JLabel();
        bviajes = new javax.swing.JLabel();
        breportes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        bsalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        bsalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bsalir1MouseEntered(evt);
            }
        });

        bcamion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autobus.png"))); // NOI18N
        bcamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcamionMouseClicked(evt);
            }
        });

        bconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conductor.png"))); // NOI18N
        bconductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bconductorMouseClicked(evt);
            }
        });

        bboleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/billete-de-avion.png"))); // NOI18N
        bboleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bboletoMouseClicked(evt);
            }
        });

        bviajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/viaje.png"))); // NOI18N
        bviajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bviajesMouseClicked(evt);
            }
        });

        breportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuenta.png"))); // NOI18N
        breportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breportesMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventana.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bcamion)
                .addGap(79, 79, 79)
                .addComponent(bboleto)
                .addGap(77, 77, 77)
                .addComponent(bconductor)
                .addGap(82, 82, 82)
                .addComponent(bviajes)
                .addGap(94, 94, 94)
                .addComponent(breportes)
                .addGap(78, 78, 78)
                .addComponent(bsalir1)
                .addGap(18, 18, 18))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bcamion)
                    .addComponent(bboleto)
                    .addComponent(bviajes)
                    .addComponent(breportes)
                    .addComponent(bsalir1)
                    .addComponent(bconductor))
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsalir1MouseClicked
        // TODO add your handling code here:
        new Menuprincipal().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bsalir1MouseClicked

    private void bsalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsalir1MouseEntered
           // TODO add your handling code here:
    }//GEN-LAST:event_bsalir1MouseEntered

    private void bcamionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcamionMouseClicked
            new BUS().setVisible(true);  this.dispose();
    }//GEN-LAST:event_bcamionMouseClicked

    private void bconductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bconductorMouseClicked
    new Conductor().setVisible(true);  this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bconductorMouseClicked

    private void bboletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bboletoMouseClicked
        new Boleto().setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_bboletoMouseClicked

    private void bviajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bviajesMouseClicked
     new Viajes().setVisible(true); this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bviajesMouseClicked

    private void breportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breportesMouseClicked
        new reportes().setVisible(true); this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_breportesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bboleto;
    private javax.swing.JLabel bcamion;
    private javax.swing.JLabel bconductor;
    private javax.swing.JLabel breportes;
    private javax.swing.JLabel bsalir1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel bviajes;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables


}
